apiVersion: argoproj . io/vlalphal
kind: Application
metadata :
name: mongodb
namespace: argocd
spec:
project: default
source :
repoURL: https://github.com/SkyDragon00/DiscountMongo
chart: grafana
targetRevision: IO. 3.1
destination :
server: https://kubernetes .default. svc
namespace: monitoring
syncP01icy:
automated :
selfHea1: true
prune: true